import express from "express";
import authRoutes from "./auth.routes.js";
import studentRoutes from "./student.routes.js";
import teacherRoutes from "./teacher.routes.js";
import classRoutes from "./class.routes.js";
import subjectRoutes from "./subject.routes.js";
import gradeRoutes from "./grade.routes.js";
import paymentRoutes from "./payment.routes.js";
import attendanceRoutes from "./attendance.routes.js";
import notificationRoutes from "./notification.routes.js";
import adminRoutes from "./admin.routes.js";
import financeRoutes from "./finance.routes.js";
import reportsRoutes from "./reports.routes.js";
import settingsRoutes from "./settings.routes.js";
import profileRoutes from "./profile.routes.js";
import studyHubRoutes from "./studyHub.routes.js";
import clubsRoutes from "./clubs.routes.js";
import kanbanRoutes from "./kanban.routes.js";
import registrationRoutes from "./registration.routes.js";

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/students", studentRoutes);
router.use("/teachers", teacherRoutes);
router.use("/classes", classRoutes);
router.use("/subjects", subjectRoutes);
router.use("/grades", gradeRoutes);
router.use("/payments", paymentRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/notifications", notificationRoutes);
router.use("/admin", adminRoutes);
router.use("/finance", financeRoutes);
router.use("/reports", reportsRoutes);
router.use("/settings", settingsRoutes);
router.use("/profile", profileRoutes);
router.use("/study-hub", studyHubRoutes);
router.use("/clubs", clubsRoutes);
router.use("/kanban", kanbanRoutes);
router.use("/registration", registrationRoutes);

export default router;
